/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetounifg;

import SIstemaCadastro.Aluno;
import SIstemaCadastro.AlunosDAO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.table.DefaultTableModel;
import projetounifg.notaAlunos;
import projetounifg.notas;

/**
 *
 * @author MatheusWP
 */
public class SistemaCadastroAlunos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public SistemaCadastroAlunos() {
        initComponents();
        listarDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        curso = new javax.swing.JComboBox<>();
        uf = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        campus = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        btn_1 = new javax.swing.JRadioButton();
        btn_3 = new javax.swing.JRadioButton();
        btn_2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        editar = new javax.swing.JToggleButton();
        excluir = new javax.swing.JToggleButton();
        cadastrar = new javax.swing.JToggleButton();
        gerar = new javax.swing.JToggleButton();
        faltas = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAlunos = new javax.swing.JTable();
        tell = new javax.swing.JFormattedTextField();
        dataNascismento = new javax.swing.JFormattedTextField();
        raAluno = new javax.swing.JFormattedTextField();
        cpf = new javax.swing.JFormattedTextField();
        municipio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(60, 85, 253));

        jPanel4.setBackground(new java.awt.Color(60, 85, 253));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cadastro de Alunos");

        jPanel2.setBackground(new java.awt.Color(60, 85, 253));
        jPanel2.setForeground(java.awt.Color.white);
        jPanel2.setToolTipText("alunos");

        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("RA:");

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Nome:");

        nomeAluno.setToolTipText("nomeAluno");

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("CPF:");

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("UF:");

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Data de nascimento:");

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Telefone:");

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Curso:");

        curso.setBackground(new java.awt.Color(255, 255, 255));
        curso.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        curso.setForeground(new java.awt.Color(0, 0, 0));
        curso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Engenharia de Software", "Ciências de Dados", "Análises e Desenvolvimento de Sistemas", "Redes de Computadores", "Engenharia de Dados", "Ciência da Computação", "Engenharia da Computação", "Gestão em Tecnologia da Informação" }));
        curso.setToolTipText("curso");
        curso.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        curso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoActionPerformed(evt);
            }
        });

        uf.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\t", "AC", "AL", "AP\t", "AM", "BA\t", "CE", "DF", "ES\t", "GO", "MA", "MT", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SP", "SE", "TO" }));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Campus:");

        campus.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        campus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Campus", "São Sebastião " }));
        campus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campusActionPerformed(evt);
            }
        });

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Período:");

        btn_1.setBackground(new java.awt.Color(60, 85, 253));
        btn_1.setForeground(java.awt.Color.white);
        btn_1.setText("Matutino");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(60, 85, 253));
        btn_3.setForeground(java.awt.Color.white);
        btn_3.setText("Noturno");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(60, 85, 253));
        btn_2.setForeground(java.awt.Color.white);
        btn_2.setText("Vespertino");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("Munícipio:");

        editar.setBackground(java.awt.Color.white);
        editar.setText("Editar Aluno");
        editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        excluir.setBackground(java.awt.Color.white);
        excluir.setText("Excluir Aluno");
        excluir.setToolTipText("");
        excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        cadastrar.setBackground(java.awt.Color.white);
        cadastrar.setText("Cadastrar Aluno");
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        gerar.setBackground(java.awt.Color.white);
        gerar.setText("Gerar Boletim");
        gerar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerarActionPerformed(evt);
            }
        });

        faltas.setBackground(java.awt.Color.white);
        faltas.setText("Faltas");
        faltas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        faltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faltasActionPerformed(evt);
            }
        });

        tbAlunos.setBackground(new java.awt.Color(60, 85, 253));
        tbAlunos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbAlunos.setForeground(java.awt.Color.white);
        tbAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RA", "Curso", "Nascimento", "Telefone", "Município", "CPF", "Período", "Campus", "UF", "Média", "Faltas", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAlunos.setToolTipText("Alunos Cadastrados");
        tbAlunos.setColumnSelectionAllowed(true);
        tbAlunos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbAlunos.setGridColor(java.awt.Color.white);
        tbAlunos.setName(""); // NOI18N
        tbAlunos.setRequestFocusEnabled(false);
        tbAlunos.setRowHeight(32);
        tbAlunos.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tbAlunos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbAlunos.setShowHorizontalLines(false);
        tbAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAlunosMouseClicked(evt);
            }
        });
        tbAlunos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbAlunosKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbAlunos);
        tbAlunos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (tbAlunos.getColumnModel().getColumnCount() > 0) {
            tbAlunos.getColumnModel().getColumn(0).setMinWidth(220);
            tbAlunos.getColumnModel().getColumn(1).setMinWidth(70);
            tbAlunos.getColumnModel().getColumn(1).setMaxWidth(200);
            tbAlunos.getColumnModel().getColumn(2).setMinWidth(160);
            tbAlunos.getColumnModel().getColumn(3).setMinWidth(100);
            tbAlunos.getColumnModel().getColumn(3).setMaxWidth(120);
            tbAlunos.getColumnModel().getColumn(4).setMinWidth(130);
            tbAlunos.getColumnModel().getColumn(4).setMaxWidth(130);
            tbAlunos.getColumnModel().getColumn(5).setMinWidth(110);
            tbAlunos.getColumnModel().getColumn(5).setMaxWidth(110);
            tbAlunos.getColumnModel().getColumn(6).setMinWidth(130);
            tbAlunos.getColumnModel().getColumn(6).setMaxWidth(140);
            tbAlunos.getColumnModel().getColumn(7).setMinWidth(90);
            tbAlunos.getColumnModel().getColumn(7).setMaxWidth(0);
            tbAlunos.getColumnModel().getColumn(8).setMinWidth(100);
            tbAlunos.getColumnModel().getColumn(9).setMinWidth(40);
            tbAlunos.getColumnModel().getColumn(9).setMaxWidth(40);
            tbAlunos.getColumnModel().getColumn(10).setMinWidth(40);
            tbAlunos.getColumnModel().getColumn(11).setMinWidth(14);
            tbAlunos.getColumnModel().getColumn(12).setMinWidth(62);
        }

        try {
            tell.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            dataNascismento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            raAluno.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(raAluno)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(dataNascismento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(183, 183, 183)
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(tell, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(curso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addGap(18, 18, 18)
                                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(122, 122, 122)
                                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115)
                        .addComponent(faltas, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(btn_1)
                                .addGap(18, 18, 18)
                                .addComponent(btn_2)
                                .addGap(18, 18, 18)
                                .addComponent(btn_3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel11)
                                        .addGap(18, 18, 18)
                                        .addComponent(municipio))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(62, 62, 62)
                                        .addComponent(jLabel5)))
                                .addGap(18, 18, 18)
                                .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(uf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(raAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataNascismento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(municipio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(curso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(btn_1)
                    .addComponent(btn_2)
                    .addComponent(btn_3)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(campus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faltas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(561, 561, 561)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1432, 685));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbAlunosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbAlunosKeyPressed

    }//GEN-LAST:event_tbAlunosKeyPressed

    private void tbAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAlunosMouseClicked
        carregarDados();
    }//GEN-LAST:event_tbAlunosMouseClicked

    private void faltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faltasActionPerformed
        if (tbAlunos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Aluno para gerenciamento de faltas.");
        };
        faltaAlunos novaJanela = new faltaAlunos();
        int rowSelected = tbAlunos.getSelectedRow();
        notas modelo = new notas();
        modelo.setNome(tbAlunos.getValueAt(rowSelected, 0).toString());
        modelo.setRa(tbAlunos.getValueAt(rowSelected, 1).toString());
        faltaAlunos faltas = new faltaAlunos();
        faltas.receberDados(modelo);
        faltas.setVisible(true);
        dispose();
    }//GEN-LAST:event_faltasActionPerformed

    private void gerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerarActionPerformed
        if (tbAlunos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um Aluno para emissão de boletim.");
        }
        notaAlunos novaJanela = new notaAlunos();
        int rowSelected = tbAlunos.getSelectedRow();
        notas modelo = new notas();
        modelo.setNome(tbAlunos.getValueAt(rowSelected, 0).toString());
        modelo.setRa(tbAlunos.getValueAt(rowSelected, 1).toString());
        notaAlunos notas = new notaAlunos();
        notas.receberDados(modelo);
        notas.setVisible(true);
        dispose();
        listarDados();

    }//GEN-LAST:event_gerarActionPerformed

    private void listarDados() {
        try {
            AlunosDAO aluno = new AlunosDAO();
            DefaultTableModel model = (DefaultTableModel) tbAlunos.getModel();
            model.setNumRows(0);

            ArrayList<Aluno> lista = (ArrayList<Aluno>) aluno.listarAluno();

            for (int num = 0; num < lista.size(); num++) {
                Aluno aluno1 = lista.get(num);
                Object[] alunos = {
                    aluno1.getNome(),
                    aluno1.getRa(),
                    aluno1.getCurso(),
                    aluno1.getData(),
                    aluno1.getTelefone(),
                    aluno1.getMunicipio(),
                    aluno1.getCpf(),
                    aluno1.getPeriodo1(),
                    aluno1.getCampus(),
                    aluno1.getUf(),
                    aluno1.getNota(),
                    aluno1.getFaltas(),
                    aluno1.getStatus(),};
                model.addRow(alunos);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "ListarDados tela" + erro);
        }

    }

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed

        String nome, ra, curso, notas, faltas, dataNascimento, tell, municipio, uf, cpf, periodo1, periodo2, periodo3, campus;

        nome = nomeAluno.getText();
        ra = raAluno.getText();
        curso = (String) this.curso.getSelectedItem();
        cpf = this.cpf.getText();
        dataNascimento = dataNascismento.getText();
        tell = this.tell.getText();
        uf = (String) this.uf.getSelectedItem();
        periodo1 = btn_1.getText();
        periodo2 = btn_2.getText();
        periodo3 = btn_3.getText();
        campus = (String) this.campus.getSelectedItem();
        municipio = this.municipio.getText();

        boolean primeiroTurno = btn_1.isSelected();
        boolean segundoTurno = btn_2.isSelected();
        boolean terceiroTurno = btn_3.isSelected();

        if (nomeAluno.getText().equals("") || raAluno.getText().equals("        ") || this.cpf.getText().equals("   .   .   -  ") || dataNascismento.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o aluno, tente novamente.");
            nomeAluno.requestFocus();
        } else if (this.curso.getSelectedItem().equals(" ") || this.uf.getSelectedItem().equals("	") || this.campus.getSelectedItem().equals("Selecione um Campus")) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o aluno, tente novamente.");
            this.curso.requestFocus();
        } else if (this.tell.getText().equals("(  )       -") || this.municipio.getText().equals("            ")) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o aluno, tente novamente.");
            this.curso.requestFocus();

        } else if (primeiroTurno == false && segundoTurno == false && terceiroTurno == false) {
            JOptionPane.showMessageDialog(null, "Não foi possível cadastrar o aluno, tente novamente.");
        } else {

            SIstemaCadastro.Aluno alunos = new Aluno();
            alunos.setNome(nome);
            alunos.setRa(ra);
            alunos.setCurso(curso);
            alunos.setData(dataNascimento);
            alunos.setTelefone(tell);
            alunos.setMunicipio(municipio);
            alunos.setCpf(cpf);
            alunos.setPeriodo1(periodo1);
            alunos.setCampus(campus);
            alunos.setUf(uf);

            SIstemaCadastro.AlunosDAO alunosDAO = new AlunosDAO();
            alunosDAO.cadastrarAluno(alunos);
            listarDados();
            limparCampos();
    }//GEN-LAST:event_cadastrarActionPerformed

    }

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        try {
            excluirAluno();
        } catch (SQLException ex) {
            Logger.getLogger(SistemaCadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarDados();
        limparCampos();
    }//GEN-LAST:event_excluirActionPerformed

    private void excluirAluno() throws SQLException {
        String ra = raAluno.getText();

        SIstemaCadastro.Aluno alunos = new Aluno();
        alunos.setRa(ra);
        SIstemaCadastro.AlunosDAO alunosDAO = new AlunosDAO();
        alunosDAO.excluirDados(alunos);

    }

    private void editarDados() throws SQLException {
        String nome, ra, curso, notas, faltas, dataNascimento, tell, municipio, uf, cpf, periodo1, periodo2, periodo3, campus;

        nome = nomeAluno.getText();
        ra = raAluno.getText();
        curso = (String) this.curso.getSelectedItem();
        cpf = this.cpf.getText();
        dataNascimento = dataNascismento.getText();
        tell = this.tell.getText();
        uf = (String) this.uf.getSelectedItem();
        periodo1 = btn_1.getText();
        periodo2 = btn_2.getText();
        periodo3 = btn_3.getText();
        campus = (String) this.campus.getSelectedItem();
        municipio = this.municipio.getText();

        boolean primeiroTurno = btn_1.isSelected();
        boolean segundoTurno = btn_2.isSelected();
        boolean terceiroTurno = btn_3.isSelected();

        if (nomeAluno.getText().equals("") || raAluno.getText().equals("        ") || this.cpf.getText().equals("   .   .   -  ") || dataNascismento.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Não foi possível editar dados do aluno, tente novamente.");
            nomeAluno.requestFocus();
        } else if (this.curso.getSelectedItem().equals(" ") || this.uf.getSelectedItem().equals("	") || this.campus.getSelectedItem().equals("Selecione um Campus")) {
            JOptionPane.showMessageDialog(null, "Não foi possível editar dados do  o aluno, tente novamente.");
            this.curso.requestFocus();
        } else if (this.tell.getText().equals("(  )       -") || this.municipio.getText().equals("            ")) {
            JOptionPane.showMessageDialog(null, "Não foi possível editar dados do  o aluno, tente novamente.");
            this.curso.requestFocus();

        } else if (primeiroTurno == false && segundoTurno == false && terceiroTurno == false) {
            JOptionPane.showMessageDialog(null, "Não foi possível editar dados do  o aluno, tente novamente.");
        } else {

            Aluno alunos = new Aluno();
            alunos.setNome(nome);
            alunos.setRa(ra);
            alunos.setCurso(curso);
            alunos.setData(dataNascimento);
            alunos.setTelefone(tell);
            alunos.setMunicipio(municipio);
            alunos.setCpf(cpf);
            alunos.setPeriodo1(periodo1);
            alunos.setPeriodo2(periodo2);
            alunos.setPeriodo3(periodo3);
            alunos.setCampus(campus);
            alunos.setUf(uf);

            SIstemaCadastro.AlunosDAO alunosDAO = new AlunosDAO();
            alunosDAO.editarDados(alunos);
        }
    }

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed

        try {
            editarDados();
            limparCampos();
        } catch (SQLException ex) {
            Logger.getLogger(SistemaCadastroAlunos.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarDados();
    }//GEN-LAST:event_editarActionPerformed

    private void limparCampos() {
        nomeAluno.setText("");
        raAluno.setText("");
        curso.setSelectedItem("");
        btn_1.setSelected(false);
        btn_2.setSelected(false);
        btn_3.setSelected(false);
        cpf.setText("");
        tell.setText("");
        dataNascismento.setText("");
        municipio.setText("");
        curso.setSelectedItem(" ");
        campus.setSelectedItem("Selecione um Campus");
        uf.setSelectedItem("	");
    }

    private void carregarDados() {
        int set = tbAlunos.getSelectedRow();
        String verificarRadio = (String) tbAlunos.getModel().getValueAt(set, 7);
        raAluno.setText(tbAlunos.getModel().getValueAt(set, 1).toString());
        nomeAluno.setText(tbAlunos.getModel().getValueAt(set, 0).toString());
        dataNascismento.setText(tbAlunos.getModel().getValueAt(set, 3).toString());
        cpf.setText(tbAlunos.getModel().getValueAt(set, 6).toString());
        curso.setSelectedItem(tbAlunos.getModel().getValueAt(set, 2).toString());
        campus.setSelectedItem(tbAlunos.getModel().getValueAt(set, 8).toString());
        municipio.setText(tbAlunos.getModel().getValueAt(set, 5).toString());
        tell.setText(tbAlunos.getModel().getValueAt(set, 4).toString());
        uf.setSelectedItem(tbAlunos.getModel().getValueAt(set, 9).toString());

        if (verificarRadio.equals("Matutino")) {
            btn_1.setSelected(true);
            btn_2.setSelected(false);
            btn_3.setSelected(false);
        } else if (verificarRadio.equals("Vespertino")) {
            btn_1.setSelected(false);
            btn_2.setSelected(true);
            btn_3.setSelected(false);
        } else if (verificarRadio.equals("Noturno")) {
            btn_1.setSelected(false);
            btn_2.setSelected(false);
            btn_3.setSelected(true);
        } else {
            JOptionPane.showMessageDialog(null, "erro");
        }
    }

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        btn_1.setSelected(false);
        btn_3.setSelected(false);
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        btn_1.setSelected(false);
        btn_2.setSelected(false);
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        btn_2.setSelected(false);
        btn_3.setSelected(false);
    }//GEN-LAST:event_btn_1ActionPerformed

    private void campusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campusActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoActionPerformed

    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaCadastroAlunos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton btn_1;
    public javax.swing.JRadioButton btn_2;
    public javax.swing.JRadioButton btn_3;
    private javax.swing.JToggleButton cadastrar;
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JComboBox<String> curso;
    private javax.swing.JFormattedTextField dataNascismento;
    private javax.swing.JToggleButton editar;
    private javax.swing.JToggleButton excluir;
    private javax.swing.JToggleButton faltas;
    private javax.swing.JToggleButton gerar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField municipio;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JFormattedTextField raAluno;
    public javax.swing.JTable tbAlunos;
    private javax.swing.JFormattedTextField tell;
    private javax.swing.JComboBox<String> uf;
    // End of variables declaration//GEN-END:variables
}
